/*
 * Innov8 Studios — RELATIONSHIPS mock data. UI/UX only, exactly like
 * Marketing's marketingMock.js: nothing here talks to Supabase, nothing
 * survives a refresh. See useRelationships.js for the local, in-memory
 * state built from this array.
 *
 * Every record shares a universal shape (identity + classification +
 * relationship context) and carries additional fields depending on
 * `type`. See relationshipsFormat.js for the helpers that read them.
 */

export const TEAM = [
  { name: "Lewis Kariuki", role: "Founder / Creative Director" },
  { name: "Wanjiru Ndegwa", role: "Client Success Lead" },
  { name: "Brian Otieno", role: "Business Development" },
  { name: "Faith Achieng", role: "Account Manager" },
  { name: "Kevin Mwas", role: "Partnerships Lead" }
];

export const TAGS = ["High Value", "Returning", "Corporate", "Startup", "Referral", "Design", "Motion", "3D", "Web", "Photography", "Partner", "Priority"];

export const SOURCES = ["Website", "Enquiry", "Instagram", "TikTok", "LinkedIn", "Referral", "Existing Client", "Direct Outreach", "Networking", "Other"];

export const SERVICES = ["Branding", "Motion Graphics", "3D Commercial", "Social Media Design", "Website Design", "Photography", "Creative Retainer"];

export const PARTNER_TYPES = ["Creative", "Production", "Technology", "Referral", "Agency", "Supplier", "Strategic"];

export const LEAD_STATUSES = ["New", "Contacted", "Qualified", "Proposal", "Won", "Lost"];

export const INTEREST_LEVELS = ["Low", "Medium", "High"];

export const PRIORITIES = ["Low", "Normal", "High"];

export const RELATIONSHIP_TYPES = ["Contact", "Prospect", "Lead", "Client", "Partner"];

let seed = 0;
function id() {
  seed += 1;
  return `rel-${seed}`;
}
function noteId() {
  seed += 1;
  return `note-${seed}`;
}
function evId() {
  seed += 1;
  return `ev-${seed}`;
}

export const RELATIONSHIPS = [
  // ───────────────────────────── CONTACTS ─────────────────────────────
  {
    id: id(),
    type: "Contact",
    active: true,
    personName: "Sarah Kimani",
    brandName: "Sarah Kimani",
    role: "",
    email: "sarah.kimani@gmail.com",
    phone: "+254 712 340 118",
    website: "",
    location: "Nairobi",
    social: "",
    owner: "Faith Achieng",
    source: "Website",
    tags: ["Design"],
    notes: [{ id: noteId(), text: "Found us through the portfolio page — asked about pricing for a personal brand site.", date: "2026-08-25", author: "Faith Achieng" }],
    interactions: [{ id: id(), type: "Enquiry", date: "2026-08-25", description: "Submitted website enquiry form", person: "Faith Achieng" }],
    events: [{ id: evId(), date: "2026-08-25", type: "created", label: "Contact created from website enquiry" }],
    nextFollowUp: "2026-09-03",
    followUpReason: "Send portfolio site pricing",
    dateAdded: "2026-08-25",
    dateUpdated: "2026-08-25",
    originContext: { kind: "enquiry", date: "2026-08-25", subject: "Portfolio website quote", service: "Website Design" }
  },
  {
    id: id(),
    type: "Contact",
    active: true,
    personName: "James Mutuku",
    brandName: "Mutuku Logistics",
    role: "Operations Manager",
    email: "james@mutukulogistics.co.ke",
    phone: "+254 720 556 883",
    website: "mutukulogistics.co.ke",
    location: "Mombasa Road, Nairobi",
    social: "",
    owner: "Brian Otieno",
    source: "Networking",
    tags: ["Corporate"],
    notes: [{ id: noteId(), text: "Met at the SME Expo — interested in a brand refresh eventually, no urgency yet.", date: "2026-08-18", author: "Brian Otieno" }],
    interactions: [{ id: id(), type: "Meeting", date: "2026-08-18", description: "Exchanged contacts at Nairobi SME Expo", person: "Brian Otieno" }],
    events: [{ id: evId(), date: "2026-08-18", type: "created", label: "Contact created from event networking" }],
    nextFollowUp: "2026-09-10",
    followUpReason: "Check in post-expo",
    dateAdded: "2026-08-18",
    dateUpdated: "2026-08-18",
    originContext: null
  },
  {
    id: id(),
    type: "Contact",
    active: true,
    personName: "Purity Wanjala",
    brandName: "Purity Wanjala",
    role: "Independent Photographer",
    email: "purity.wanjala@outlook.com",
    phone: "+254 733 118 442",
    website: "",
    location: "Kilimani, Nairobi",
    social: "@puritywanjala",
    owner: "Kevin Mwas",
    source: "Instagram",
    tags: ["Photography", "Referral"],
    notes: [{ id: noteId(), text: "DM'd asking if we take freelance photographers for overflow shoots.", date: "2026-08-29", author: "Kevin Mwas" }],
    interactions: [{ id: id(), type: "Message", date: "2026-08-29", description: "Instagram DM introduction", person: "Kevin Mwas" }],
    events: [{ id: evId(), date: "2026-08-29", type: "created", label: "Contact created from Instagram" }],
    nextFollowUp: "2026-09-05",
    followUpReason: "Review portfolio, gauge partner fit",
    dateAdded: "2026-08-29",
    dateUpdated: "2026-08-29",
    originContext: null
  },
  {
    id: id(),
    type: "Contact",
    active: true,
    personName: "Dennis Otieno",
    brandName: "Craft & Co.",
    role: "Co-founder",
    email: "dennis@craftandco.co.ke",
    phone: "+254 701 224 590",
    website: "craftandco.co.ke",
    location: "Westlands, Nairobi",
    social: "",
    owner: "Brian Otieno",
    source: "LinkedIn",
    tags: ["Startup"],
    notes: [],
    interactions: [{ id: id(), type: "Message", date: "2026-08-30", description: "Connected on LinkedIn, brief intro exchange", person: "Brian Otieno" }],
    events: [{ id: evId(), date: "2026-08-30", type: "created", label: "Contact created from LinkedIn" }],
    nextFollowUp: null,
    followUpReason: null,
    dateAdded: "2026-08-30",
    dateUpdated: "2026-08-30",
    originContext: null
  },
  {
    id: id(),
    type: "Contact",
    active: true,
    personName: "Halima Noor",
    brandName: "Halima Noor",
    role: "",
    email: "halima.noor@gmail.com",
    phone: "+254 715 902 337",
    website: "",
    location: "Nairobi",
    social: "@halimacreates",
    owner: "Faith Achieng",
    source: "Instagram",
    tags: [],
    notes: [{ id: noteId(), text: "Commented on a reel asking who did the motion work — casual interest so far.", date: "2026-08-22", author: "Faith Achieng" }],
    interactions: [{ id: id(), type: "Message", date: "2026-08-22", description: "Replied to her comment, offered to share more work", person: "Faith Achieng" }],
    events: [{ id: evId(), date: "2026-08-22", type: "created", label: "Contact created from Instagram" }],
    nextFollowUp: "2026-08-29",
    followUpReason: "Follow up on shared reel — no response yet",
    dateAdded: "2026-08-22",
    dateUpdated: "2026-08-22",
    originContext: null
  },
  {
    id: id(),
    type: "Contact",
    active: false,
    personName: "George Kamau",
    brandName: "Kamau & Sons Hardware",
    role: "Owner",
    email: "george@kamauhardware.co.ke",
    phone: "+254 722 447 610",
    website: "",
    location: "Ngong Road, Nairobi",
    social: "",
    owner: "Brian Otieno",
    source: "Referral",
    tags: [],
    notes: [{ id: noteId(), text: "Referred by Loft Interiors — said budget is tied up until next year.", date: "2026-07-30", author: "Brian Otieno" }],
    interactions: [{ id: id(), type: "Call", date: "2026-07-30", description: "Introductory call, revisit in 2027", person: "Brian Otieno" }],
    events: [
      { id: evId(), date: "2026-07-28", type: "created", label: "Contact created via referral" },
      { id: evId(), date: "2026-07-30", type: "status_change", label: "Marked Inactive — revisit next budget cycle" }
    ],
    nextFollowUp: null,
    followUpReason: null,
    dateAdded: "2026-07-28",
    dateUpdated: "2026-07-30",
    originContext: null
  },

  // ───────────────────────────── PROSPECTS ─────────────────────────────
  {
    id: id(),
    type: "Prospect",
    active: true,
    personName: "Zawadi Mumo",
    brandName: "Zawadi Interiors",
    role: "Creative Director",
    email: "zawadi@zawadiinteriors.co.ke",
    phone: "+254 733 208 771",
    website: "zawadiinteriors.co.ke",
    location: "Karen, Nairobi",
    social: "@zawadiinteriors",
    owner: "Kevin Mwas",
    source: "Instagram",
    tags: ["Design", "High Value"],
    potentialService: "Branding",
    interestLevel: "High",
    priority: "High",
    notes: [{ id: noteId(), text: "Growing interiors studio, rebrand ahead of their showroom opening in October.", date: "2026-08-27", author: "Kevin Mwas" }],
    interactions: [
      { id: id(), type: "Outreach", date: "2026-08-20", description: "Instagram DM opener sent", person: "Kevin Mwas" },
      { id: id(), type: "Message", date: "2026-08-27", description: "Replied — asked for a rebrand portfolio", person: "Kevin Mwas" }
    ],
    events: [{ id: evId(), date: "2026-08-20", type: "created", label: "Prospect created from outreach" }],
    nextFollowUp: "2026-09-02",
    followUpReason: "Send rebrand case studies",
    dateAdded: "2026-08-20",
    dateUpdated: "2026-08-27",
    originContext: { kind: "outreach", campaign: "Branding for Startups", lastOutreach: "2026-08-27", status: "Responded", response: "Interested, wants case studies", nextAction: "Send rebrand portfolio" }
  },
  {
    id: id(),
    type: "Prospect",
    active: true,
    personName: "Michael Kiptoo",
    brandName: "TechHub Nairobi",
    role: "Community Manager",
    email: "michael@techhubnairobi.co.ke",
    phone: "+254 700 118 226",
    website: "techhubnairobi.co.ke",
    location: "Upper Hill, Nairobi",
    social: "",
    owner: "Brian Otieno",
    source: "LinkedIn",
    tags: ["Web", "Startup"],
    potentialService: "Website Design",
    interestLevel: "Medium",
    priority: "Normal",
    notes: [{ id: noteId(), text: "Coworking space looking to refresh their membership site before Q4.", date: "2026-08-24", author: "Brian Otieno" }],
    interactions: [{ id: id(), type: "Outreach", date: "2026-08-24", description: "LinkedIn connection + intro message", person: "Brian Otieno" }],
    events: [{ id: evId(), date: "2026-08-24", type: "created", label: "Prospect created from outreach" }],
    nextFollowUp: "2026-09-04",
    followUpReason: "Follow up on intro message",
    dateAdded: "2026-08-24",
    dateUpdated: "2026-08-24",
    originContext: { kind: "outreach", campaign: "Website Design Sprint", lastOutreach: "2026-08-24", status: "Sent", response: "", nextAction: "Follow up if no reply by Sept 4" }
  },
  {
    id: id(),
    type: "Prospect",
    active: true,
    personName: "Amara Njeri",
    brandName: "Amara Skincare",
    role: "Founder",
    email: "amara@amaraskincare.co.ke",
    phone: "+254 711 447 990",
    website: "",
    location: "Lavington, Nairobi",
    social: "@amaraskincare",
    owner: "Faith Achieng",
    source: "Instagram",
    tags: ["Startup", "Design"],
    potentialService: "Social Media Design",
    interestLevel: "Medium",
    priority: "Normal",
    notes: [],
    interactions: [{ id: id(), type: "Outreach", date: "2026-08-30", description: "Instagram DM sent introducing our social design work", person: "Faith Achieng" }],
    events: [{ id: evId(), date: "2026-08-30", type: "created", label: "Prospect created from outreach" }],
    nextFollowUp: "2026-09-06",
    followUpReason: "Check for a reply",
    dateAdded: "2026-08-30",
    dateUpdated: "2026-08-30",
    originContext: { kind: "outreach", campaign: "Social Media Design Showcase", lastOutreach: "2026-08-30", status: "Sent", response: "", nextAction: "Await reply" }
  },
  {
    id: id(),
    type: "Prospect",
    active: true,
    personName: "Collins Wafula",
    brandName: "Rafiki Logistics",
    role: "Marketing Lead",
    email: "collins@rafikilogistics.co.ke",
    phone: "+254 722 908 114",
    website: "rafikilogistics.co.ke",
    location: "Industrial Area, Nairobi",
    social: "",
    owner: "Kevin Mwas",
    source: "Direct Outreach",
    tags: ["Motion", "Corporate"],
    potentialService: "Motion Graphics",
    interestLevel: "Low",
    priority: "Low",
    notes: [{ id: noteId(), text: "Cold email — no response yet, low priority for now.", date: "2026-08-19", author: "Kevin Mwas" }],
    interactions: [{ id: id(), type: "Outreach", date: "2026-08-19", description: "Cold email sent", person: "Kevin Mwas" }],
    events: [{ id: evId(), date: "2026-08-19", type: "created", label: "Prospect created from outreach" }],
    nextFollowUp: "2026-08-28",
    followUpReason: "Second-touch follow-up email",
    dateAdded: "2026-08-19",
    dateUpdated: "2026-08-19",
    originContext: { kind: "outreach", campaign: "Motion / 3D Commercials", lastOutreach: "2026-08-19", status: "Sent", response: "", nextAction: "Second-touch email" }
  },
  {
    id: id(),
    type: "Prospect",
    active: true,
    personName: "Naomi Chege",
    brandName: "Nomad Coffee Roasters",
    role: "Owner",
    email: "naomi@nomadcoffee.co.ke",
    phone: "+254 706 337 224",
    website: "nomadcoffee.co.ke",
    location: "Kilimani, Nairobi",
    social: "@nomadcoffeeke",
    owner: "Wanjiru Ndegwa",
    source: "Referral",
    tags: ["High Value", "Referral"],
    potentialService: "Branding",
    interestLevel: "High",
    priority: "High",
    notes: [{ id: noteId(), text: "Referred by Nairobi Coffee Collective — opening a second branch, wants full rebrand + web.", date: "2026-08-28", author: "Wanjiru Ndegwa" }],
    interactions: [{ id: id(), type: "Call", date: "2026-08-28", description: "Intro call — scoping rebrand + website", person: "Wanjiru Ndegwa" }],
    events: [{ id: evId(), date: "2026-08-28", type: "created", label: "Prospect created from client referral" }],
    nextFollowUp: "2026-09-03",
    followUpReason: "Send proposal outline",
    dateAdded: "2026-08-28",
    dateUpdated: "2026-08-28",
    originContext: null
  },

  // ─────────────────────────────── LEADS ───────────────────────────────
  {
    id: id(),
    type: "Lead",
    active: true,
    personName: "Jane Wanjiku",
    brandName: "Acme Creative Ltd",
    role: "Marketing Lead",
    email: "jane@acmecreative.co.ke",
    phone: "+254 711 220 340",
    website: "acmecreative.co.ke",
    location: "Westlands, Nairobi",
    social: "@acmecreativeke",
    owner: "Kevin Mwas",
    source: "Instagram",
    tags: ["High Value", "Motion"],
    opportunity: "Rebrand + launch commercial",
    serviceInterest: "Motion Graphics",
    estimatedValue: 480000,
    status: "Qualified",
    priority: "High",
    notes: [{ id: noteId(), text: "Qualified after the discovery call — budget confirmed, wants proposal by end of week.", date: "2026-08-31", author: "Kevin Mwas" }],
    interactions: [
      { id: id(), type: "Outreach", date: "2026-08-22", description: "Instagram DM opener sent", person: "Kevin Mwas" },
      { id: id(), type: "Message", date: "2026-08-26", description: "Replied — interested, asked for a call", person: "Kevin Mwas" },
      { id: id(), type: "Call", date: "2026-08-31", description: "Discovery call — scoped rebrand + launch commercial", person: "Kevin Mwas" }
    ],
    events: [
      { id: evId(), date: "2026-08-22", type: "created", label: "Prospect created from Instagram outreach" },
      { id: evId(), date: "2026-08-26", type: "status_change", label: "Converted from Prospect to Lead" },
      { id: evId(), date: "2026-08-31", type: "status_change", label: "Lead status set to Qualified" }
    ],
    nextFollowUp: "2026-09-05",
    followUpReason: "Send proposal",
    dateAdded: "2026-08-22",
    dateUpdated: "2026-08-31",
    originContext: { kind: "outreach", campaign: "Instagram DM Outreach — Sept", lastOutreach: "2026-08-31", status: "Responded", response: "Budget confirmed, wants proposal", nextAction: "Send proposal by Sept 5" }
  },
  {
    id: id(),
    type: "Lead",
    active: true,
    personName: "David Otieno",
    brandName: "Nike Kenya",
    role: "Brand Activation Manager",
    email: "david.otieno@nike-partner.co.ke",
    phone: "+254 733 902 117",
    website: "",
    location: "Nairobi",
    social: "",
    owner: "Lewis Kariuki",
    source: "Direct Outreach",
    tags: ["High Value", "Corporate", "3D"],
    opportunity: "3D product showcase for regional launch",
    serviceInterest: "3D Commercial",
    estimatedValue: 1250000,
    status: "Proposal",
    priority: "Urgent",
    notes: [{ id: noteId(), text: "Proposal sent — awaiting sign-off from their regional team.", date: "2026-08-30", author: "Lewis Kariuki" }],
    interactions: [
      { id: id(), type: "Meeting", date: "2026-08-15", description: "Scoping meeting at their office", person: "Lewis Kariuki" },
      { id: id(), type: "Email", date: "2026-08-30", description: "Sent formal proposal + budget breakdown", person: "Lewis Kariuki" }
    ],
    events: [
      { id: evId(), date: "2026-08-10", type: "created", label: "Lead created from direct outreach" },
      { id: evId(), date: "2026-08-30", type: "proposal", label: "Proposal sent" }
    ],
    nextFollowUp: "2026-09-02",
    followUpReason: "Follow up on proposal sign-off",
    dateAdded: "2026-08-10",
    dateUpdated: "2026-08-30",
    originContext: null
  },
  {
    id: id(),
    type: "Lead",
    active: true,
    personName: "Caroline Wambui",
    brandName: "Simba Savings SACCO",
    role: "Head of Marketing",
    email: "caroline@simbasavings.co.ke",
    phone: "+254 722 774 511",
    website: "simbasavings.co.ke",
    location: "CBD, Nairobi",
    social: "",
    owner: "Brian Otieno",
    source: "LinkedIn",
    tags: ["Corporate", "High Value"],
    opportunity: "Full brand identity refresh",
    serviceInterest: "Branding",
    estimatedValue: 620000,
    status: "New",
    priority: "Normal",
    notes: [{ id: noteId(), text: "High-value target — needs a tailored, formal first approach.", date: "2026-08-31", author: "Brian Otieno" }],
    interactions: [],
    events: [{ id: evId(), date: "2026-08-31", type: "created", label: "Lead created from LinkedIn research" }],
    nextFollowUp: "2026-09-03",
    followUpReason: "Send formal introduction",
    dateAdded: "2026-08-31",
    dateUpdated: "2026-08-31",
    originContext: null
  },
  {
    id: id(),
    type: "Lead",
    active: true,
    personName: "Peter Njuguna",
    brandName: "GreenPath Farms",
    role: "Managing Director",
    email: "peter@greenpathfarms.co.ke",
    phone: "+254 720 664 229",
    website: "greenpathfarms.co.ke",
    location: "Kiambu",
    social: "",
    owner: "Wanjiru Ndegwa",
    source: "Enquiry",
    tags: ["Web", "Corporate"],
    opportunity: "E-commerce site for farm produce",
    serviceInterest: "Website Design",
    estimatedValue: 340000,
    status: "Contacted",
    priority: "Normal",
    notes: [{ id: noteId(), text: "Enquired via the website form, replied with a discovery call invite.", date: "2026-08-27", author: "Wanjiru Ndegwa" }],
    interactions: [{ id: id(), type: "Email", date: "2026-08-27", description: "Replied to enquiry, proposed a call", person: "Wanjiru Ndegwa" }],
    events: [{ id: evId(), date: "2026-08-25", type: "created", label: "Lead created from website enquiry" }],
    nextFollowUp: "2026-09-01",
    followUpReason: "Confirm discovery call time",
    dateAdded: "2026-08-25",
    dateUpdated: "2026-08-27",
    originContext: { kind: "enquiry", date: "2026-08-25", subject: "E-commerce site quote", service: "Website Design" }
  },
  {
    id: id(),
    type: "Lead",
    active: true,
    personName: "Kevin Mwangi",
    brandName: "Bloom Events Co",
    role: "Creative Director",
    email: "kevin@bloomevents.co.ke",
    phone: "+254 724 883 105",
    website: "bloomevents.co.ke",
    location: "Kilimani, Nairobi",
    social: "@bloomeventsco",
    owner: "Kevin Mwas",
    source: "Instagram",
    tags: ["Returning", "High Value"],
    opportunity: "Monthly content retainer",
    serviceInterest: "Creative Retainer",
    estimatedValue: 900000,
    status: "Won",
    priority: "High",
    notes: [{ id: noteId(), text: "Signed the retainer agreement — moving to Client onboarding this week.", date: "2026-08-29", author: "Kevin Mwas" }],
    interactions: [
      { id: id(), type: "Meeting", date: "2026-08-22", description: "Retainer scope call", person: "Kevin Mwas" },
      { id: id(), type: "Email", date: "2026-08-29", description: "Signed agreement received", person: "Kevin Mwas" }
    ],
    events: [
      { id: evId(), date: "2026-08-05", type: "created", label: "Lead created from Instagram outreach" },
      { id: evId(), date: "2026-08-29", type: "status_change", label: "Lead status set to Won" }
    ],
    nextFollowUp: "2026-09-02",
    followUpReason: "Kick off onboarding, convert to Client",
    dateAdded: "2026-08-05",
    dateUpdated: "2026-08-29",
    originContext: null
  },
  {
    id: id(),
    type: "Lead",
    active: false,
    personName: "Mercy Adhiambo",
    brandName: "Urban Nest Realty",
    role: "Director",
    email: "mercy@urbannest.co.ke",
    phone: "+254 710 664 229",
    website: "",
    location: "Nairobi",
    social: "",
    owner: "Brian Otieno",
    source: "WhatsApp",
    tags: [],
    opportunity: "Property listing microsite",
    serviceInterest: "Website Design",
    estimatedValue: 220000,
    status: "Lost",
    priority: "Low",
    notes: [{ id: noteId(), text: "Budget allocated elsewhere this term — revisit in the new year.", date: "2026-08-15", author: "Brian Otieno" }],
    interactions: [{ id: id(), type: "Message", date: "2026-08-15", description: "Declined for now, will revisit January", person: "Brian Otieno" }],
    events: [
      { id: evId(), date: "2026-08-10", type: "created", label: "Lead created from WhatsApp outreach" },
      { id: evId(), date: "2026-08-15", type: "status_change", label: "Lead status set to Lost" }
    ],
    nextFollowUp: null,
    followUpReason: null,
    dateAdded: "2026-08-10",
    dateUpdated: "2026-08-15",
    originContext: null
  },

  // ─────────────────────────────── CLIENTS ───────────────────────────────
  {
    id: id(),
    type: "Client",
    active: true,
    personName: "Brian Odhiambo",
    brandName: "Nairobi Coffee Collective",
    role: "Founder",
    email: "brian@nairobicoffee.co.ke",
    phone: "+254 722 118 904",
    website: "nairobicoffee.co.ke",
    location: "Westlands, Nairobi",
    social: "@nairobicoffeeco",
    owner: "Wanjiru Ndegwa",
    source: "Enquiry",
    tags: ["Returning", "High Value", "Design"],
    servicesUsed: ["Branding", "Social Media Design", "Website Design"],
    projects: [
      { id: id(), name: "Westlands Branch Rebrand", status: "Active", startDate: "2026-08-01", endDate: "2026-09-30", value: 420000 },
      { id: id(), name: "Instagram Grid Refresh", status: "Completed", startDate: "2026-05-01", endDate: "2026-06-10", value: 180000 },
      { id: id(), name: "Menu & Packaging Design", status: "Completed", startDate: "2026-02-15", endDate: "2026-03-20", value: 150000 }
    ],
    clientSince: "2026-02-01",
    relationshipHealth: "Healthy",
    notes: [{ id: noteId(), text: "Long-standing client — always quick to approve and pays on time.", date: "2026-08-20", author: "Wanjiru Ndegwa" }],
    interactions: [
      { id: id(), type: "Meeting", date: "2026-08-20", description: "Progress review for Westlands rebrand", person: "Wanjiru Ndegwa" },
      { id: id(), type: "Email", date: "2026-08-26", description: "Shared first round of rebrand concepts", person: "Wanjiru Ndegwa" }
    ],
    events: [
      { id: evId(), date: "2026-02-01", type: "status_change", label: "Converted from Lead to Client" },
      { id: evId(), date: "2026-02-15", type: "project_started", label: "Project started — Menu & Packaging Design" },
      { id: evId(), date: "2026-03-20", type: "project_completed", label: "Project completed — Menu & Packaging Design" },
      { id: evId(), date: "2026-05-01", type: "project_started", label: "Project started — Instagram Grid Refresh" },
      { id: evId(), date: "2026-06-10", type: "project_completed", label: "Project completed — Instagram Grid Refresh" },
      { id: evId(), date: "2026-08-01", type: "project_started", label: "Project started — Westlands Branch Rebrand" }
    ],
    nextFollowUp: "2026-09-08",
    followUpReason: "Review second round of rebrand concepts",
    dateAdded: "2026-01-20",
    dateUpdated: "2026-08-26",
    originContext: { kind: "enquiry", date: "2026-01-15", subject: "Menu & packaging design quote", service: "Branding" }
  },
  {
    id: id(),
    type: "Client",
    active: true,
    personName: "Grace Chebet",
    brandName: "Savanna Fitness Club",
    role: "Marketing Coordinator",
    email: "grace@savannafitness.co.ke",
    phone: "+254 701 992 340",
    website: "savannafitness.co.ke",
    location: "Kilimani, Nairobi",
    social: "@savannafitnessclub",
    owner: "Kevin Mwas",
    source: "Instagram",
    tags: ["Motion", "3D"],
    servicesUsed: ["3D Commercial"],
    projects: [{ id: id(), name: "New Studio Launch Commercial", status: "Active", startDate: "2026-08-10", endDate: "2026-09-25", value: 310000 }],
    clientSince: "2026-08-05",
    relationshipHealth: "Healthy",
    notes: [{ id: noteId(), text: "Converted after the follow-up nudge — first project underway.", date: "2026-08-10", author: "Kevin Mwas" }],
    interactions: [{ id: id(), type: "Meeting", date: "2026-08-10", description: "Kickoff call for the launch commercial", person: "Kevin Mwas" }],
    events: [
      { id: evId(), date: "2026-08-05", type: "status_change", label: "Converted from Lead to Client" },
      { id: evId(), date: "2026-08-10", type: "project_started", label: "Project started — New Studio Launch Commercial" }
    ],
    nextFollowUp: "2026-09-04",
    followUpReason: "Check rough cut approval",
    dateAdded: "2026-07-18",
    dateUpdated: "2026-08-10",
    originContext: null
  },
  {
    id: id(),
    type: "Client",
    active: true,
    personName: "Diana Wafula",
    brandName: "Equity Heights Realty",
    role: "Sales & Marketing Manager",
    email: "diana@equityheights.co.ke",
    phone: "+254 733 118 660",
    website: "equityheights.co.ke",
    location: "Kilimani, Nairobi",
    social: "",
    owner: "Wanjiru Ndegwa",
    source: "LinkedIn",
    tags: ["Corporate", "3D"],
    servicesUsed: ["3D Commercial", "Social Media Design"],
    projects: [
      { id: id(), name: "Kiambu Road Show-Unit Walkthrough", status: "Active", startDate: "2026-07-20", endDate: "2026-09-15", value: 380000 },
      { id: id(), name: "Listings Social Campaign", status: "Completed", startDate: "2026-04-01", endDate: "2026-05-10", value: 140000 }
    ],
    clientSince: "2026-04-01",
    relationshipHealth: "At Risk",
    notes: [{ id: noteId(), text: "Walkthrough revisions are dragging — client has gone quiet on the last two rounds of feedback.", date: "2026-08-28", author: "Wanjiru Ndegwa" }],
    interactions: [
      { id: id(), type: "Email", date: "2026-08-18", description: "Sent second revision of the 3D walkthrough", person: "Wanjiru Ndegwa" },
      { id: id(), type: "Call", date: "2026-08-28", description: "Left voicemail, no response yet", person: "Wanjiru Ndegwa" }
    ],
    events: [
      { id: evId(), date: "2026-04-01", type: "status_change", label: "Converted from Lead to Client" },
      { id: evId(), date: "2026-04-01", type: "project_started", label: "Project started — Listings Social Campaign" },
      { id: evId(), date: "2026-05-10", type: "project_completed", label: "Project completed — Listings Social Campaign" },
      { id: evId(), date: "2026-07-20", type: "project_started", label: "Project started — Kiambu Road Show-Unit Walkthrough" }
    ],
    nextFollowUp: "2026-08-30",
    followUpReason: "Escalate — no response to two revision rounds",
    dateAdded: "2026-03-10",
    dateUpdated: "2026-08-28",
    originContext: null
  },
  {
    id: id(),
    type: "Client",
    active: true,
    personName: "Faith Mumbi",
    brandName: "Baraka Foods",
    role: "Brand Manager",
    email: "faith@barakafoods.co.ke",
    phone: "+254 715 330 776",
    website: "barakafoods.co.ke",
    location: "Industrial Area, Nairobi",
    social: "",
    owner: "Faith Achieng",
    source: "Enquiry",
    tags: ["Corporate"],
    servicesUsed: ["Motion Graphics"],
    projects: [{ id: id(), name: "Product Launch Commercial", status: "Completed", startDate: "2026-05-01", endDate: "2026-06-15", value: 260000 }],
    clientSince: "2026-05-01",
    relationshipHealth: "Inactive",
    notes: [{ id: noteId(), text: "No new briefs since the launch commercial wrapped — worth a check-in before year end.", date: "2026-07-25", author: "Faith Achieng" }],
    interactions: [{ id: id(), type: "Email", date: "2026-06-20", description: "Sent final delivery + thank you note", person: "Faith Achieng" }],
    events: [
      { id: evId(), date: "2026-05-01", type: "status_change", label: "Converted from Lead to Client" },
      { id: evId(), date: "2026-05-01", type: "project_started", label: "Project started — Product Launch Commercial" },
      { id: evId(), date: "2026-06-15", type: "project_completed", label: "Project completed — Product Launch Commercial" }
    ],
    nextFollowUp: "2026-09-15",
    followUpReason: "Re-engagement check-in",
    dateAdded: "2026-04-20",
    dateUpdated: "2026-07-25",
    originContext: null
  },
  {
    id: id(),
    type: "Client",
    active: true,
    personName: "Kevin Mwas",
    brandName: "Loft Interiors",
    role: "Creative Director",
    email: "kevin@loftinteriors.co.ke",
    phone: "+254 724 883 105",
    website: "loftinteriors.co.ke",
    location: "Karen, Nairobi",
    social: "@loftinteriors",
    owner: "Kevin Mwas",
    source: "Instagram",
    tags: ["Returning", "High Value", "Design"],
    servicesUsed: ["Creative Retainer", "Photography"],
    projects: [
      { id: id(), name: "Monthly Content Retainer — Q3", status: "Active", startDate: "2026-07-01", endDate: "2026-09-30", value: 450000 },
      { id: id(), name: "Showroom Photography Day", status: "Completed", startDate: "2026-06-05", endDate: "2026-06-05", value: 90000 }
    ],
    clientSince: "2026-06-01",
    relationshipHealth: "Healthy",
    notes: [{ id: noteId(), text: "Wants an ongoing monthly content retainer — one of our most reliable clients.", date: "2026-08-15", author: "Kevin Mwas" }],
    interactions: [{ id: id(), type: "Meeting", date: "2026-08-15", description: "Monthly retainer planning call", person: "Kevin Mwas" }],
    events: [
      { id: evId(), date: "2026-06-01", type: "status_change", label: "Converted from Lead to Client" },
      { id: evId(), date: "2026-06-05", type: "project_started", label: "Project started — Showroom Photography Day" },
      { id: evId(), date: "2026-06-05", type: "project_completed", label: "Project completed — Showroom Photography Day" },
      { id: evId(), date: "2026-07-01", type: "project_started", label: "Project started — Monthly Content Retainer — Q3" }
    ],
    nextFollowUp: "2026-09-01",
    followUpReason: "Plan October retainer content calendar",
    dateAdded: "2026-05-20",
    dateUpdated: "2026-08-15",
    originContext: null
  },
  {
    id: id(),
    type: "Client",
    active: true,
    personName: "Dennis Kiptoo",
    brandName: "Pesa Point Fintech",
    role: "Head of Growth",
    email: "dennis@pesapoint.co.ke",
    phone: "+254 706 552 981",
    website: "pesapoint.co.ke",
    location: "Upper Hill, Nairobi",
    social: "",
    owner: "Lewis Kariuki",
    source: "Enquiry",
    tags: ["Corporate", "Web", "High Value"],
    servicesUsed: ["Website Design"],
    projects: [{ id: id(), name: "Landing Page Refresh — Series A", status: "Active", startDate: "2026-08-05", endDate: "2026-09-20", value: 520000 }],
    clientSince: "2026-08-01",
    relationshipHealth: "Healthy",
    notes: [{ id: noteId(), text: "Wanted a landing page refresh ahead of their Series A push — moving fast.", date: "2026-08-05", author: "Lewis Kariuki" }],
    interactions: [{ id: id(), type: "Meeting", date: "2026-08-05", description: "Kickoff call for landing page refresh", person: "Lewis Kariuki" }],
    events: [
      { id: evId(), date: "2026-08-01", type: "status_change", label: "Converted from Lead to Client" },
      { id: evId(), date: "2026-08-05", type: "project_started", label: "Project started — Landing Page Refresh — Series A" }
    ],
    nextFollowUp: "2026-09-03",
    followUpReason: "Review first design draft",
    dateAdded: "2026-07-31",
    dateUpdated: "2026-08-05",
    originContext: { kind: "enquiry", date: "2026-07-31", subject: "Landing page refresh quote", service: "Website Design" }
  },

  // ─────────────────────────────── PARTNERS ───────────────────────────────
  {
    id: id(),
    type: "Partner",
    active: true,
    personName: "Esther Nyambura",
    brandName: "Kaleido Photography Studio",
    role: "Lead Photographer",
    email: "esther@kaleidostudio.co.ke",
    phone: "+254 720 118 774",
    website: "kaleidostudio.co.ke",
    location: "Kilimani, Nairobi",
    social: "@kaleidostudioke",
    owner: "Kevin Mwas",
    source: "Referral",
    tags: ["Photography", "Partner"],
    partnerType: "Creative",
    capabilities: ["Product Photography", "Event Photography"],
    notes: [{ id: noteId(), text: "Our go-to photographer for overflow shoots — reliable turnaround.", date: "2026-06-10", author: "Kevin Mwas" }],
    interactions: [{ id: id(), type: "Meeting", date: "2026-08-12", description: "Discussed availability for Sept shoots", person: "Kevin Mwas" }],
    events: [{ id: evId(), date: "2026-03-15", type: "created", label: "Partner relationship established" }],
    nextFollowUp: "2026-09-12",
    followUpReason: "Confirm Sept shoot availability",
    dateAdded: "2026-03-15",
    dateUpdated: "2026-08-12",
    originContext: null
  },
  {
    id: id(),
    type: "Partner",
    active: true,
    personName: "Samuel Kariuki",
    brandName: "Vantage Productions",
    role: "Producer",
    email: "samuel@vantageproductions.co.ke",
    phone: "+254 720 556 812",
    website: "vantageproductions.co.ke",
    location: "Lavington, Nairobi",
    social: "",
    owner: "Lewis Kariuki",
    source: "Existing Client",
    tags: ["Partner", "Motion"],
    partnerType: "Production",
    capabilities: ["Video Production", "Equipment Rental", "Crew Sourcing"],
    notes: [{ id: noteId(), text: "Started as a client, now our regular production crew partner for larger commercial shoots.", date: "2026-07-05", author: "Lewis Kariuki" }],
    interactions: [{ id: id(), type: "Call", date: "2026-08-20", description: "Booked crew for Nike Kenya shoot pending sign-off", person: "Lewis Kariuki" }],
    events: [{ id: evId(), date: "2026-01-10", type: "created", label: "Converted from Client to Partner" }],
    nextFollowUp: "2026-09-02",
    followUpReason: "Confirm crew booking for Nike shoot",
    dateAdded: "2026-01-10",
    dateUpdated: "2026-08-20",
    originContext: null
  },
  {
    id: id(),
    type: "Partner",
    active: true,
    personName: "Njoroge Kamau",
    brandName: "CodeCraft Devs",
    role: "Technical Lead",
    email: "njoroge@codecraftdevs.co.ke",
    phone: "+254 733 447 118",
    website: "codecraftdevs.co.ke",
    location: "Remote / Nairobi",
    social: "",
    owner: "Brian Otieno",
    source: "Direct Outreach",
    tags: ["Web", "Partner"],
    partnerType: "Technology",
    capabilities: ["Custom Web Development", "E-commerce Builds"],
    notes: [{ id: noteId(), text: "Dev partner for projects needing custom backend work beyond our website design scope.", date: "2026-05-22", author: "Brian Otieno" }],
    interactions: [{ id: id(), type: "Email", date: "2026-08-14", description: "Scoped backend work for a future e-commerce build", person: "Brian Otieno" }],
    events: [{ id: evId(), date: "2026-05-22", type: "created", label: "Partner relationship established" }],
    nextFollowUp: null,
    followUpReason: null,
    dateAdded: "2026-05-22",
    dateUpdated: "2026-08-14",
    originContext: null
  },
  {
    id: id(),
    type: "Partner",
    active: true,
    personName: "Winnie Achieng",
    brandName: "Two Rivers Agency",
    role: "Partnerships Manager",
    email: "winnie@tworiversagency.co.ke",
    phone: "+254 711 774 220",
    website: "tworiversagency.co.ke",
    location: "Two Rivers, Nairobi",
    social: "",
    owner: "Kevin Mwas",
    source: "Networking",
    tags: ["Referral", "Partner", "Corporate"],
    partnerType: "Referral",
    capabilities: ["Overflow Referrals", "Joint Pitches"],
    notes: [{ id: noteId(), text: "Sends us overflow branding work when their in-house team is at capacity.", date: "2026-06-30", author: "Kevin Mwas" }],
    interactions: [{ id: id(), type: "Meeting", date: "2026-08-01", description: "Quarterly partner check-in", person: "Kevin Mwas" }],
    events: [{ id: evId(), date: "2026-02-20", type: "created", label: "Partner relationship established" }],
    nextFollowUp: "2026-11-01",
    followUpReason: "Next quarterly check-in",
    dateAdded: "2026-02-20",
    dateUpdated: "2026-08-01",
    originContext: null
  },
  {
    id: id(),
    type: "Partner",
    active: false,
    personName: "Paul Mwangi",
    brandName: "PrintWorks Kenya",
    role: "Account Manager",
    email: "paul@printworks.co.ke",
    phone: "+254 700 220 445",
    website: "printworks.co.ke",
    location: "Industrial Area, Nairobi",
    social: "",
    owner: "Faith Achieng",
    source: "Referral",
    tags: ["Partner"],
    partnerType: "Supplier",
    capabilities: ["Large-format Printing", "Packaging Print"],
    notes: [{ id: noteId(), text: "Went quiet after pricing became uncompetitive — no active jobs routed to them since June.", date: "2026-07-01", author: "Faith Achieng" }],
    interactions: [],
    events: [
      { id: evId(), date: "2026-01-15", type: "created", label: "Partner relationship established" },
      { id: evId(), date: "2026-07-01", type: "status_change", label: "Marked Inactive — pricing no longer competitive" }
    ],
    nextFollowUp: null,
    followUpReason: null,
    dateAdded: "2026-01-15",
    dateUpdated: "2026-07-01",
    originContext: null
  }
];
