-- 0012: project_activity — append-only event log per project.
--
-- Deliberately NOT writable by any client INSERT policy at all. Every row
-- is produced by a SECURITY DEFINER trigger below, which always stamps
-- auth.uid() itself — a user can never forge another user's actor, and
-- there is no "forgotten frontend call" that silently drops an event,
-- because the events are generated by the database, not by studio.js.

create table public.project_activity (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  type text not null check (
    type in (
      'project_created', 'status_changed', 'priority_changed',
      'milestone_created', 'milestone_completed', 'assignment_changed',
      'file_uploaded', 'comment_added'
    )
  ),
  actor_profile_id uuid references public.profiles (id) on delete set null,
  description text not null,
  visibility text not null default 'internal' check (visibility in ('internal', 'client')),
  created_at timestamptz not null default now()
);

comment on table public.project_activity is
  'Append-only. No UPDATE/DELETE policy exists for any role — history cannot be edited or removed via the API, only inserted by the trigger functions below.';

create index project_activity_project_id_idx on public.project_activity (project_id);

alter table public.project_activity enable row level security;

create policy project_activity_select on public.project_activity
  for select to authenticated
  using (public.is_internal_user());

-- No INSERT/UPDATE/DELETE policy for any role. All rows come from the
-- SECURITY DEFINER log_activity() below, which bypasses RLS by design.

-- ---------- the one function every trigger below funnels through ----------

create or replace function public.log_activity(
  p_project_id uuid,
  p_type text,
  p_description text,
  p_visibility text default 'internal'
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.project_activity (project_id, type, actor_profile_id, description, visibility)
  values (p_project_id, p_type, auth.uid(), p_description, p_visibility);
end;
$$;

-- ---------- project_created ----------

create or replace function public.trg_project_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.log_activity(new.id, 'project_created', 'Project created', 'internal');
  return new;
end;
$$;

create trigger project_activity_on_created
  after insert on public.projects
  for each row execute function public.trg_project_created();

-- ---------- status_changed / priority_changed ----------

create or replace function public.trg_project_status_changed()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_label text;
begin
  if new.status_id is distinct from old.status_id then
    select label into v_label from public.project_option_lists where id = new.status_id;
    perform public.log_activity(new.id, 'status_changed', 'Status changed to ' || coalesce(v_label, '—'), 'internal');
  end if;
  if new.priority_id is distinct from old.priority_id then
    select label into v_label from public.project_option_lists where id = new.priority_id;
    perform public.log_activity(new.id, 'priority_changed', 'Priority changed to ' || coalesce(v_label, '—'), 'internal');
  end if;
  return new;
end;
$$;

create trigger project_activity_on_status_priority_change
  after update on public.projects
  for each row execute function public.trg_project_status_changed();

-- ---------- milestone_created / milestone_completed ----------

create or replace function public.trg_milestone_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.log_activity(new.project_id, 'milestone_created', 'Milestone "' || new.title || '" created', 'internal');
  return new;
end;
$$;

create trigger project_activity_on_milestone_created
  after insert on public.milestones
  for each row execute function public.trg_milestone_created();

create or replace function public.trg_milestone_completed()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_label text;
begin
  if new.status_id is distinct from old.status_id then
    select label into v_label from public.project_option_lists where id = new.status_id;
    if v_label = 'Completed' then
      perform public.log_activity(new.project_id, 'milestone_completed', 'Milestone "' || new.title || '" completed', 'client');
    end if;
  end if;
  return new;
end;
$$;

create trigger project_activity_on_milestone_completed
  after update on public.milestones
  for each row execute function public.trg_milestone_completed();

-- ---------- assignment_changed ----------

create or replace function public.trg_project_member_changed()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_project_id uuid;
  v_name text;
  v_verb text;
begin
  if tg_op = 'INSERT' then
    v_project_id := new.project_id;
    select full_name into v_name from public.team_members where id = new.team_member_id;
    v_verb := 'added to';
  else
    v_project_id := old.project_id;
    select full_name into v_name from public.team_members where id = old.team_member_id;
    v_verb := 'removed from';
  end if;
  perform public.log_activity(v_project_id, 'assignment_changed', coalesce(v_name, 'Someone') || ' ' || v_verb || ' the project team', 'internal');
  return coalesce(new, old);
end;
$$;

create trigger project_activity_on_member_change
  after insert or delete on public.project_members
  for each row execute function public.trg_project_member_changed();

-- ---------- file_uploaded ----------

create or replace function public.trg_file_uploaded()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.log_activity(
    new.project_id,
    'file_uploaded',
    'Uploaded ' || new.original_filename,
    case when new.visibility = 'Client' then 'client' else 'internal' end
  );
  return new;
end;
$$;

create trigger project_activity_on_file_uploaded
  after insert on public.project_files
  for each row execute function public.trg_file_uploaded();

-- ---------- comment_added ----------

create or replace function public.trg_comment_added()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.log_activity(
    new.project_id,
    'comment_added',
    new.author_display_name || ' commented',
    case when new.author_type = 'client' then 'client' else 'internal' end
  );
  return new;
end;
$$;

create trigger project_activity_on_comment_added
  after insert on public.project_comments
  for each row execute function public.trg_comment_added();
