/*
 * Innov8 Studios — ENQUIRIES mock data. UI/UX only, exactly like
 * Marketing's marketingMock.js and Relationships' relationshipsMock.js:
 * nothing here talks to Supabase, nothing survives a refresh. See
 * useEnquiries.js for the local, in-memory state built from this array.
 *
 * Enquiries is the intake funnel: Incoming Interest → Qualification →
 * Follow-up → Conversion → Relationship. A converted enquiry does NOT
 * create a second person/company record here — it just records which
 * Relationship type it became (see `conversion`), so a future backend
 * can point that at the canonical Relationships record instead of
 * inventing a competing one.
 */

export const TEAM = [
  { name: "Lewis Kariuki", role: "Founder / Creative Director" },
  { name: "Wanjiru Ndegwa", role: "Client Success Lead" },
  { name: "Brian Otieno", role: "Business Development" },
  { name: "Faith Achieng", role: "Account Manager" },
  { name: "Kevin Mwas", role: "Partnerships Lead" }
];

export const SOURCES = ["Website", "Instagram", "TikTok", "Facebook", "WhatsApp", "Referral", "Direct", "Campaign", "Outreach", "Other"];

export const SERVICES = ["Branding", "Social Media Design", "Motion Graphics", "3D", "Video / Commercials", "Printing", "Web Design", "Other"];

export const STATUSES = ["New", "Contacted", "Qualifying", "Qualified", "Converted", "Closed"];

export const PRIORITIES = ["Low", "Normal", "High", "Urgent"];

export const CONVERSION_TYPES = ["Contact", "Prospect", "Lead", "Client", "Partner"];

let seed = 0;
function id() {
  seed += 1;
  return `enq-${seed}`;
}
function noteId() {
  seed += 1;
  return `enqnote-${seed}`;
}
function evId() {
  seed += 1;
  return `enqev-${seed}`;
}

export const ENQUIRIES = [
  // ─────────────────────────────── NEW ───────────────────────────────
  {
    id: id(),
    personName: "Wambui Kariuki",
    brandName: "Two Rivers Mall — Retail Marketing",
    email: "wambui@tworiversmall.co.ke",
    phone: "+254 712 440 118",
    location: "Ruaka, Nairobi",
    message: "Looking for a design partner to handle our monthly in-mall promotional graphics and digital screens content.",
    services: ["Social Media Design", "Printing"],
    source: "Website",
    dateReceived: "2026-08-31",
    status: "New",
    priority: "Normal",
    owner: "Faith Achieng",
    estimatedValue: null,
    desiredTimeline: "",
    qualificationNotes: "",
    nextFollowUp: "2026-09-03",
    followUpNote: "First response to enquiry form",
    notes: [],
    events: [{ id: evId(), date: "2026-08-31", type: "received", label: "Enquiry received via website form" }],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Tony Kiplangat",
    brandName: "Highland Dairy Co-op",
    email: "tony@highlanddairy.co.ke",
    phone: "+254 733 220 774",
    location: "Nakuru",
    message: "Need a brand refresh for our packaging ahead of a national retail rollout.",
    services: ["Branding", "Printing"],
    source: "Referral",
    dateReceived: "2026-08-31",
    status: "New",
    priority: "High",
    owner: "Wanjiru Ndegwa",
    estimatedValue: 450000,
    desiredTimeline: "Within 6 weeks",
    qualificationNotes: "",
    nextFollowUp: "2026-09-02",
    followUpNote: "Call to scope packaging rollout",
    notes: [],
    events: [{ id: evId(), date: "2026-08-31", type: "received", label: "Enquiry received via referral" }],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Millicent Auma",
    brandName: "Millicent Auma",
    email: "millicent.auma@gmail.com",
    phone: "+254 700 118 552",
    location: "Kisumu",
    message: "Hi, I'm launching a small skincare line and need a logo and Instagram templates.",
    services: ["Branding", "Social Media Design"],
    source: "Instagram",
    dateReceived: "2026-08-30",
    status: "New",
    priority: "Low",
    owner: "Faith Achieng",
    estimatedValue: null,
    desiredTimeline: "Flexible",
    qualificationNotes: "",
    nextFollowUp: "2026-09-04",
    followUpNote: "Reply with starter package pricing",
    notes: [],
    events: [{ id: evId(), date: "2026-08-30", type: "received", label: "Enquiry received via Instagram DM" }],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Dennis Muriithi",
    brandName: "Muriithi & Partners Advocates",
    email: "dennis@muriithipartners.co.ke",
    phone: "+254 720 447 220",
    location: "Upper Hill, Nairobi",
    message: "Our website looks dated — want a quote for a full redesign, ideally launching before year-end.",
    services: ["Web Design"],
    source: "Website",
    dateReceived: "2026-08-29",
    status: "New",
    priority: "Normal",
    owner: "Brian Otieno",
    estimatedValue: 380000,
    desiredTimeline: "Before December",
    qualificationNotes: "",
    nextFollowUp: "2026-09-02",
    followUpNote: "Send discovery call invite",
    notes: [],
    events: [{ id: evId(), date: "2026-08-29", type: "received", label: "Enquiry received via website form" }],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Aisha Mohamed",
    brandName: "Coral Coast Resort",
    email: "aisha@coralcoastresort.co.ke",
    phone: "+254 722 990 441",
    location: "Diani, Mombasa",
    message: "We'd like a promotional video for the resort ahead of the December holiday season.",
    services: ["Video / Commercials"],
    source: "Facebook",
    dateReceived: "2026-08-28",
    status: "New",
    priority: "High",
    owner: "Kevin Mwas",
    estimatedValue: 620000,
    desiredTimeline: "Ready by late November",
    qualificationNotes: "",
    nextFollowUp: "2026-09-01",
    followUpNote: "Call to discuss shoot logistics in Diani",
    notes: [],
    events: [{ id: evId(), date: "2026-08-28", type: "received", label: "Enquiry received via Facebook page" }],
    conversion: null,
    originCampaign: null
  },

  // ─────────────────────────────── CONTACTED ───────────────────────────────
  {
    id: id(),
    personName: "Brian Otieno",
    brandName: "Apex Media Group",
    email: "brian@apexmedia.co.ke",
    phone: "+254 711 774 220",
    location: "Westlands, Nairobi",
    message: "We're a media agency looking for a 3D subcontractor for a car dealership client's showroom visuals.",
    services: ["3D"],
    source: "Direct",
    dateReceived: "2026-08-25",
    status: "Contacted",
    priority: "Normal",
    owner: "Kevin Mwas",
    estimatedValue: 290000,
    desiredTimeline: "Next 4 weeks",
    qualificationNotes: "",
    nextFollowUp: "2026-09-05",
    followUpNote: "Awaiting their client's brief document",
    notes: [{ id: noteId(), text: "Replied with our 3D showreel — waiting on their client's brief.", date: "2026-08-26", author: "Kevin Mwas" }],
    events: [
      { id: evId(), date: "2026-08-25", type: "received", label: "Enquiry received via direct email" },
      { id: evId(), date: "2026-08-26", type: "contacted", label: "Replied with 3D showreel" }
    ],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Amina Wanjiku",
    brandName: "Kijiji Foods",
    email: "amina@kijijifoods.co.ke",
    phone: "+254 733 118 226",
    location: "Industrial Area, Nairobi",
    message: "We need packaging design for a new snack line launching in supermarkets.",
    services: ["Branding", "Printing"],
    source: "Website",
    dateReceived: "2026-08-24",
    status: "Contacted",
    priority: "High",
    owner: "Wanjiru Ndegwa",
    estimatedValue: 340000,
    desiredTimeline: "Launch in October",
    qualificationNotes: "",
    nextFollowUp: "2026-09-01",
    followUpNote: "Confirm scope call time",
    notes: [{ id: noteId(), text: "Called to introduce ourselves, proposed a scope call for early September.", date: "2026-08-25", author: "Wanjiru Ndegwa" }],
    events: [
      { id: evId(), date: "2026-08-24", type: "received", label: "Enquiry received via website form" },
      { id: evId(), date: "2026-08-25", type: "contacted", label: "Introductory call made" }
    ],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Peter Kamau",
    brandName: "Savanna Ridge Estate",
    email: "peter@savannaridge.co.ke",
    phone: "+254 706 224 118",
    location: "Kiambu Road, Nairobi",
    message: "Interested in social media management for our new gated community launch.",
    services: ["Social Media Design"],
    source: "Instagram",
    dateReceived: "2026-08-23",
    status: "Contacted",
    priority: "Normal",
    owner: "Faith Achieng",
    estimatedValue: 260000,
    desiredTimeline: "Start ASAP",
    qualificationNotes: "",
    nextFollowUp: "2026-08-30",
    followUpNote: "Second follow-up — no reply to first message",
    notes: [{ id: noteId(), text: "Sent our social media package deck, no reply yet.", date: "2026-08-24", author: "Faith Achieng" }],
    events: [
      { id: evId(), date: "2026-08-23", type: "received", label: "Enquiry received via Instagram DM" },
      { id: evId(), date: "2026-08-24", type: "contacted", label: "Sent social media package deck" }
    ],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Ruth Njoki",
    brandName: "Ruth Njoki Events",
    email: "ruth@ruthnjokievents.co.ke",
    phone: "+254 715 662 440",
    location: "Karen, Nairobi",
    message: "Need motion graphics for event recap reels for corporate clients.",
    services: ["Motion Graphics"],
    source: "TikTok",
    dateReceived: "2026-08-22",
    status: "Contacted",
    priority: "Low",
    owner: "Kevin Mwas",
    estimatedValue: 120000,
    desiredTimeline: "Ongoing, per event",
    qualificationNotes: "",
    nextFollowUp: "2026-09-06",
    followUpNote: "Check interest after sample reel sent",
    notes: [{ id: noteId(), text: "Sent a sample recap reel from a past event.", date: "2026-08-23", author: "Kevin Mwas" }],
    events: [
      { id: evId(), date: "2026-08-22", type: "received", label: "Enquiry received via TikTok comment" },
      { id: evId(), date: "2026-08-23", type: "contacted", label: "Sent sample recap reel" }
    ],
    conversion: null,
    originCampaign: null
  },

  // ─────────────────────────────── QUALIFYING ───────────────────────────────
  {
    id: id(),
    personName: "Samuel Gitau",
    brandName: "Gitau Motors",
    email: "samuel@gitaumotors.co.ke",
    phone: "+254 722 118 774",
    location: "Mombasa Road, Nairobi",
    message: "We want a full commercial video campaign for our new SUV lineup.",
    services: ["Video / Commercials", "Motion Graphics"],
    source: "Referral",
    dateReceived: "2026-08-18",
    status: "Qualifying",
    priority: "High",
    owner: "Lewis Kariuki",
    estimatedValue: 980000,
    desiredTimeline: "Campaign launch in October",
    qualificationNotes: "Budget looks credible — verifying decision-maker and confirming shoot locations before proposal.",
    nextFollowUp: "2026-09-03",
    followUpNote: "Confirm shoot locations with their ops team",
    notes: [
      { id: noteId(), text: "Discovery call held — strong budget signal, needs internal sign-off from their MD.", date: "2026-08-20", author: "Lewis Kariuki" }
    ],
    events: [
      { id: evId(), date: "2026-08-18", type: "received", label: "Enquiry received via referral" },
      { id: evId(), date: "2026-08-19", type: "contacted", label: "Initial call scheduled" },
      { id: evId(), date: "2026-08-20", type: "qualifying", label: "Moved to Qualifying — discovery call held" }
    ],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Naomi Wairimu",
    brandName: "Zuri Beauty Bar",
    email: "naomi@zuribeautybar.co.ke",
    phone: "+254 733 990 224",
    location: "Kilimani, Nairobi",
    message: "Rebrand for our salon chain — 3 branches, need consistent identity across all of them.",
    services: ["Branding"],
    source: "Instagram",
    dateReceived: "2026-08-19",
    status: "Qualifying",
    priority: "Normal",
    owner: "Wanjiru Ndegwa",
    estimatedValue: 410000,
    desiredTimeline: "Q4 2026",
    qualificationNotes: "Checking budget against scope — 3-branch rollout may need phased pricing.",
    nextFollowUp: "2026-09-02",
    followUpNote: "Send phased pricing options",
    notes: [{ id: noteId(), text: "Scoping call done — proposing phased rollout across the 3 branches.", date: "2026-08-21", author: "Wanjiru Ndegwa" }],
    events: [
      { id: evId(), date: "2026-08-19", type: "received", label: "Enquiry received via Instagram DM" },
      { id: evId(), date: "2026-08-21", type: "qualifying", label: "Moved to Qualifying — scoping call held" }
    ],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Isaac Cheruiyot",
    brandName: "Rift Valley Grains",
    email: "isaac@riftvalleygrains.co.ke",
    phone: "+254 720 774 118",
    location: "Eldoret",
    message: "Website + basic e-commerce for our grain distribution business.",
    services: ["Web Design"],
    source: "Campaign",
    dateReceived: "2026-08-17",
    status: "Qualifying",
    priority: "Normal",
    owner: "Brian Otieno",
    estimatedValue: 300000,
    desiredTimeline: "Within 2 months",
    qualificationNotes: "Legitimate business, verifying e-commerce payment requirements before quoting.",
    nextFollowUp: "2026-09-04",
    followUpNote: "Confirm payment gateway requirements",
    notes: [{ id: noteId(), text: "Came in through the Website Design Sprint campaign — good fit, clarifying e-commerce needs.", date: "2026-08-19", author: "Brian Otieno" }],
    events: [
      { id: evId(), date: "2026-08-17", type: "received", label: "Enquiry received via Website Design Sprint campaign" },
      { id: evId(), date: "2026-08-19", type: "qualifying", label: "Moved to Qualifying" }
    ],
    conversion: null,
    originCampaign: "Website Design Sprint"
  },

  // ─────────────────────────────── QUALIFIED ───────────────────────────────
  {
    id: id(),
    personName: "Caroline Njeri",
    brandName: "Amref Health Africa",
    email: "caroline.njeri@amref.org",
    phone: "+254 722 447 990",
    location: "Nairobi",
    message: "Need a video series for a public health awareness campaign, multi-language.",
    services: ["Video / Commercials", "Motion Graphics"],
    source: "Outreach",
    dateReceived: "2026-08-10",
    status: "Qualified",
    priority: "Urgent",
    owner: "Lewis Kariuki",
    estimatedValue: 1450000,
    desiredTimeline: "Launch aligned to World Health Day activities",
    qualificationNotes: "Confirmed budget and mandate. Proposal in progress — high-value, NGO procurement process may add lead time.",
    nextFollowUp: "2026-08-29",
    followUpNote: "Chase procurement sign-off — overdue",
    notes: [
      { id: noteId(), text: "Budget and scope confirmed with their comms director. Drafting formal proposal.", date: "2026-08-22", author: "Lewis Kariuki" }
    ],
    events: [
      { id: evId(), date: "2026-08-10", type: "received", label: "Enquiry received via outbound outreach" },
      { id: evId(), date: "2026-08-12", type: "contacted", label: "Intro call held" },
      { id: evId(), date: "2026-08-22", type: "qualified", label: "Marked Qualified — budget and mandate confirmed" }
    ],
    conversion: null,
    originCampaign: "Direct Outreach — NGO Sector"
  },
  {
    id: id(),
    personName: "Victor Omondi",
    brandName: "Two Rivers Mall — Retail Marketing",
    email: "victor@tworiversmall.co.ke",
    phone: "+254 733 220 118",
    location: "Ruaka, Nairobi",
    message: "Separate from Wambui's enquiry — we also need signage and large-format print for the atrium.",
    services: ["Printing"],
    source: "Referral",
    dateReceived: "2026-08-15",
    status: "Qualified",
    priority: "Normal",
    owner: "Faith Achieng",
    estimatedValue: 210000,
    desiredTimeline: "Before mall's anniversary event",
    qualificationNotes: "Same brand as an earlier enquiry — flagged for the account team to coordinate a single proposal.",
    nextFollowUp: "2026-09-03",
    followUpNote: "Send combined proposal with the promo graphics enquiry",
    notes: [{ id: noteId(), text: "Confirmed budget for signage — recommend bundling with the promotional graphics enquiry from the same mall.", date: "2026-08-20", author: "Faith Achieng" }],
    events: [
      { id: evId(), date: "2026-08-15", type: "received", label: "Enquiry received via referral" },
      { id: evId(), date: "2026-08-18", type: "contacted", label: "Site visit scheduled" },
      { id: evId(), date: "2026-08-20", type: "qualified", label: "Marked Qualified — budget confirmed" }
    ],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Grace Wanjiru",
    brandName: "Nomad Coffee Roasters",
    email: "grace@nomadcoffee.co.ke",
    phone: "+254 706 337 224",
    location: "Kilimani, Nairobi",
    message: "Second branch opening — want full rebrand and a new website.",
    services: ["Branding", "Web Design"],
    source: "Referral",
    dateReceived: "2026-08-14",
    status: "Qualified",
    priority: "High",
    owner: "Wanjiru Ndegwa",
    estimatedValue: 520000,
    desiredTimeline: "Branch opens November",
    qualificationNotes: "Referred by an existing client — fast-tracked. Proposal ready to send.",
    nextFollowUp: "2026-09-02",
    followUpNote: "Send final proposal",
    notes: [{ id: noteId(), text: "Referred by Nairobi Coffee Collective — strong fit, proposal nearly ready.", date: "2026-08-21", author: "Wanjiru Ndegwa" }],
    events: [
      { id: evId(), date: "2026-08-14", type: "received", label: "Enquiry received via client referral" },
      { id: evId(), date: "2026-08-16", type: "contacted", label: "Intro call held" },
      { id: evId(), date: "2026-08-21", type: "qualified", label: "Marked Qualified" }
    ],
    conversion: null,
    originCampaign: null
  },

  // ─────────────────────────────── CONVERTED ───────────────────────────────
  {
    id: id(),
    personName: "Brian Odhiambo",
    brandName: "Nairobi Coffee Collective",
    email: "brian@nairobicoffee.co.ke",
    phone: "+254 722 118 904",
    location: "Westlands, Nairobi",
    message: "Menu and packaging design for our Westlands cafe.",
    services: ["Branding"],
    source: "Website",
    dateReceived: "2026-01-15",
    status: "Converted",
    priority: "Normal",
    owner: "Wanjiru Ndegwa",
    estimatedValue: 150000,
    desiredTimeline: "Before menu relaunch",
    qualificationNotes: "Clear scope and budget from the first call.",
    nextFollowUp: null,
    followUpNote: null,
    notes: [{ id: noteId(), text: "Converted to Client after signing off on the packaging proposal.", date: "2026-02-01", author: "Wanjiru Ndegwa" }],
    events: [
      { id: evId(), date: "2026-01-15", type: "received", label: "Enquiry received via website form" },
      { id: evId(), date: "2026-01-18", type: "contacted", label: "Intro call held" },
      { id: evId(), date: "2026-01-25", type: "qualified", label: "Marked Qualified" },
      { id: evId(), date: "2026-02-01", type: "converted", label: "Converted to Client" }
    ],
    conversion: { type: "Client", brandName: "Nairobi Coffee Collective", owner: "Wanjiru Ndegwa", date: "2026-02-01" },
    originCampaign: null
  },
  {
    id: id(),
    personName: "David Otieno",
    brandName: "Nike Kenya",
    email: "david.otieno@nike-partner.co.ke",
    phone: "+254 733 902 117",
    location: "Nairobi",
    message: "Enquiring about a 3D product showcase for a regional launch.",
    services: ["3D"],
    source: "Direct",
    dateReceived: "2026-08-10",
    status: "Converted",
    priority: "Urgent",
    owner: "Lewis Kariuki",
    estimatedValue: 1250000,
    desiredTimeline: "Regional launch window",
    qualificationNotes: "High-value corporate opportunity, fast-tracked to Lead.",
    nextFollowUp: "2026-09-02",
    followUpNote: "Follow up on proposal sign-off",
    notes: [{ id: noteId(), text: "Converted to Lead — proposal sent, awaiting regional sign-off.", date: "2026-08-10", author: "Lewis Kariuki" }],
    events: [
      { id: evId(), date: "2026-08-10", type: "received", label: "Enquiry received via direct outreach" },
      { id: evId(), date: "2026-08-10", type: "converted", label: "Converted to Lead" }
    ],
    conversion: { type: "Lead", brandName: "Nike Kenya", owner: "Lewis Kariuki", date: "2026-08-10" },
    originCampaign: null
  },
  {
    id: id(),
    personName: "Kevin Mwangi",
    brandName: "Bloom Events Co",
    email: "kevin@bloomevents.co.ke",
    phone: "+254 724 883 105",
    location: "Kilimani, Nairobi",
    message: "Looking for a creative partner for ongoing monthly content.",
    services: ["Motion Graphics", "Social Media Design"],
    source: "Instagram",
    dateReceived: "2026-08-05",
    status: "Converted",
    priority: "High",
    owner: "Kevin Mwas",
    estimatedValue: 900000,
    desiredTimeline: "Start immediately",
    qualificationNotes: "Strong repeat-business signal from the first call.",
    nextFollowUp: null,
    followUpNote: null,
    notes: [{ id: noteId(), text: "Signed a monthly retainer — converted to Lead, will move to Client on contract signature.", date: "2026-08-29", author: "Kevin Mwas" }],
    events: [
      { id: evId(), date: "2026-08-05", type: "received", label: "Enquiry received via Instagram DM" },
      { id: evId(), date: "2026-08-22", type: "qualified", label: "Marked Qualified" },
      { id: evId(), date: "2026-08-29", type: "converted", label: "Converted to Lead" }
    ],
    conversion: { type: "Lead", brandName: "Bloom Events Co", owner: "Kevin Mwas", date: "2026-08-29" },
    originCampaign: null
  },
  {
    id: id(),
    personName: "Esther Nyambura",
    brandName: "Kaleido Photography Studio",
    email: "esther@kaleidostudio.co.ke",
    phone: "+254 720 118 774",
    location: "Kilimani, Nairobi",
    message: "Would love to collaborate — we take on overflow product and event photography.",
    services: ["Other"],
    source: "Referral",
    dateReceived: "2026-03-10",
    status: "Converted",
    priority: "Normal",
    owner: "Kevin Mwas",
    estimatedValue: null,
    desiredTimeline: "Ongoing",
    qualificationNotes: "Not a client opportunity — genuine collaborator fit.",
    nextFollowUp: null,
    followUpNote: null,
    notes: [{ id: noteId(), text: "Converted to Partner — now our go-to overflow photographer.", date: "2026-03-15", author: "Kevin Mwas" }],
    events: [
      { id: evId(), date: "2026-03-10", type: "received", label: "Enquiry received via referral" },
      { id: evId(), date: "2026-03-15", type: "converted", label: "Converted to Partner" }
    ],
    conversion: { type: "Partner", brandName: "Kaleido Photography Studio", owner: "Kevin Mwas", date: "2026-03-15" },
    originCampaign: null
  },
  {
    id: id(),
    personName: "Zawadi Mumo",
    brandName: "Zawadi Interiors",
    email: "zawadi@zawadiinteriors.co.ke",
    phone: "+254 733 208 771",
    location: "Karen, Nairobi",
    message: "Rebrand ahead of our showroom opening in October — saw your work on Instagram.",
    services: ["Branding"],
    source: "Instagram",
    dateReceived: "2026-08-20",
    status: "Converted",
    priority: "High",
    owner: "Kevin Mwas",
    estimatedValue: null,
    desiredTimeline: "Before October opening",
    qualificationNotes: "Replied with interest, converted early to track as a Prospect while scoping continues.",
    nextFollowUp: "2026-09-02",
    followUpNote: "Send rebrand case studies",
    notes: [{ id: noteId(), text: "Converted to Prospect — case studies requested, scoping the rebrand.", date: "2026-08-27", author: "Kevin Mwas" }],
    events: [
      { id: evId(), date: "2026-08-20", type: "received", label: "Enquiry received via Instagram DM" },
      { id: evId(), date: "2026-08-27", type: "converted", label: "Converted to Prospect" }
    ],
    conversion: { type: "Prospect", brandName: "Zawadi Interiors", owner: "Kevin Mwas", date: "2026-08-27" },
    originCampaign: null
  },
  {
    id: id(),
    personName: "James Mutuku",
    brandName: "Mutuku Logistics",
    email: "james@mutukulogistics.co.ke",
    phone: "+254 720 556 883",
    location: "Mombasa Road, Nairobi",
    message: "Met at the SME Expo — interested in a brand refresh at some point.",
    services: ["Branding"],
    source: "Direct",
    dateReceived: "2026-08-18",
    status: "Converted",
    priority: "Low",
    owner: "Brian Otieno",
    estimatedValue: null,
    desiredTimeline: "No urgency",
    qualificationNotes: "No active opportunity yet — logged as a Contact to nurture.",
    nextFollowUp: "2026-09-10",
    followUpNote: "Check in post-expo",
    notes: [{ id: noteId(), text: "Converted to Contact — casual interest, nurture over time.", date: "2026-08-18", author: "Brian Otieno" }],
    events: [
      { id: evId(), date: "2026-08-18", type: "received", label: "Enquiry received via event networking" },
      { id: evId(), date: "2026-08-18", type: "converted", label: "Converted to Contact" }
    ],
    conversion: { type: "Contact", brandName: "Mutuku Logistics", owner: "Brian Otieno", date: "2026-08-18" },
    originCampaign: null
  },

  // ─────────────────────────────── CLOSED / LOST ───────────────────────────────
  {
    id: id(),
    personName: "Mercy Adhiambo",
    brandName: "Urban Nest Realty",
    email: "mercy@urbannest.co.ke",
    phone: "+254 710 664 229",
    location: "Nairobi",
    message: "Interested in a property listing microsite.",
    services: ["Web Design"],
    source: "WhatsApp",
    dateReceived: "2026-08-08",
    status: "Closed",
    priority: "Low",
    owner: "Brian Otieno",
    estimatedValue: 220000,
    desiredTimeline: "This quarter",
    qualificationNotes: "Budget allocated elsewhere this term — revisit in the new year.",
    nextFollowUp: null,
    followUpNote: null,
    notes: [{ id: noteId(), text: "Closed — no budget this term, flagged to revisit January.", date: "2026-08-15", author: "Brian Otieno" }],
    events: [
      { id: evId(), date: "2026-08-08", type: "received", label: "Enquiry received via WhatsApp" },
      { id: evId(), date: "2026-08-12", type: "contacted", label: "Intro call held" },
      { id: evId(), date: "2026-08-15", type: "closed", label: "Closed / Lost — budget allocated elsewhere" }
    ],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Mercy Wangari",
    brandName: "Little Nairobi Preschool",
    email: "mercy@littlenairobi.co.ke",
    phone: "+254 710 664 229",
    location: "Nairobi",
    message: "Interested in social media design for our admissions campaign.",
    services: ["Social Media Design"],
    source: "WhatsApp",
    dateReceived: "2026-08-10",
    status: "Closed",
    priority: "Low",
    owner: "Faith Achieng",
    estimatedValue: 90000,
    desiredTimeline: "This term",
    qualificationNotes: "Went quiet after pricing was shared.",
    nextFollowUp: null,
    followUpNote: null,
    notes: [{ id: noteId(), text: "No response after two follow-ups — closing for now.", date: "2026-08-15", author: "Faith Achieng" }],
    events: [
      { id: evId(), date: "2026-08-10", type: "received", label: "Enquiry received via WhatsApp" },
      { id: evId(), date: "2026-08-12", type: "contacted", label: "Sent pricing" },
      { id: evId(), date: "2026-08-15", type: "closed", label: "Closed / Lost — went unresponsive" }
    ],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Collins Wafula",
    brandName: "Rafiki Logistics",
    email: "collins@rafikilogistics.co.ke",
    phone: "+254 722 908 114",
    location: "Industrial Area, Nairobi",
    message: "Enquiring about a motion graphics explainer for our services.",
    services: ["Motion Graphics"],
    source: "Outreach",
    dateReceived: "2026-08-05",
    status: "Closed",
    priority: "Low",
    owner: "Kevin Mwas",
    estimatedValue: 150000,
    desiredTimeline: "No firm date",
    qualificationNotes: "Never responded to outreach follow-ups.",
    nextFollowUp: null,
    followUpNote: null,
    notes: [{ id: noteId(), text: "No response to two outreach touches — closing.", date: "2026-08-19", author: "Kevin Mwas" }],
    events: [
      { id: evId(), date: "2026-08-05", type: "received", label: "Enquiry received via outbound outreach" },
      { id: evId(), date: "2026-08-19", type: "closed", label: "Closed / Lost — unresponsive" }
    ],
    conversion: null,
    originCampaign: "Motion / 3D Commercials"
  },
  {
    id: id(),
    personName: "Peter Njuguna",
    brandName: "Equity Heights Realty",
    email: "peter@equityheights.co.ke",
    phone: "+254 733 118 660",
    location: "Kilimani, Nairobi",
    message: "Enquiring about additional social content beyond our current listings campaign.",
    services: ["Social Media Design"],
    source: "Referral",
    dateReceived: "2026-07-28",
    status: "Closed",
    priority: "Normal",
    owner: "Wanjiru Ndegwa",
    estimatedValue: 140000,
    desiredTimeline: "This quarter",
    qualificationNotes: "Decided to handle in-house instead.",
    nextFollowUp: null,
    followUpNote: null,
    notes: [{ id: noteId(), text: "Client opted to bring social content in-house — closing this enquiry.", date: "2026-08-02", author: "Wanjiru Ndegwa" }],
    events: [
      { id: evId(), date: "2026-07-28", type: "received", label: "Enquiry received via referral" },
      { id: evId(), date: "2026-08-02", type: "closed", label: "Closed / Lost — handled in-house" }
    ],
    conversion: null,
    originCampaign: null
  },

  // ────────────────────────── MORE NEW / RECENT (breadth) ──────────────────────────
  {
    id: id(),
    personName: "Halima Noor",
    brandName: "Halima Noor",
    email: "halima.noor@gmail.com",
    phone: "+254 715 902 337",
    location: "Nairobi",
    message: "Who did the motion work on your last reel? I might need something similar for a personal project.",
    services: ["Motion Graphics"],
    source: "Instagram",
    dateReceived: "2026-08-22",
    status: "New",
    priority: "Low",
    owner: "Faith Achieng",
    estimatedValue: null,
    desiredTimeline: "",
    qualificationNotes: "",
    nextFollowUp: "2026-08-29",
    followUpNote: "Follow up on shared reel — no response yet",
    notes: [],
    events: [{ id: evId(), date: "2026-08-22", type: "received", label: "Enquiry received via Instagram comment" }],
    conversion: null,
    originCampaign: null
  },
  {
    id: id(),
    personName: "Dennis Kiptoo",
    brandName: "Pesa Point Fintech",
    email: "dennis@pesapoint.co.ke",
    phone: "+254 706 552 981",
    location: "Upper Hill, Nairobi",
    message: "Wanting a landing page refresh ahead of our Series A push.",
    services: ["Web Design"],
    source: "Website",
    dateReceived: "2026-07-31",
    status: "Converted",
    priority: "High",
    owner: "Lewis Kariuki",
    estimatedValue: 520000,
    desiredTimeline: "Before Series A announcement",
    qualificationNotes: "Fast-moving startup, converted quickly.",
    nextFollowUp: "2026-09-03",
    followUpNote: "Review first design draft",
    notes: [{ id: noteId(), text: "Converted to Client — kicked off the landing page refresh.", date: "2026-08-01", author: "Lewis Kariuki" }],
    events: [
      { id: evId(), date: "2026-07-31", type: "received", label: "Enquiry received via website form" },
      { id: evId(), date: "2026-08-01", type: "converted", label: "Converted to Client" }
    ],
    conversion: { type: "Client", brandName: "Pesa Point Fintech", owner: "Lewis Kariuki", date: "2026-08-01" },
    originCampaign: null
  },
  {
    id: id(),
    personName: "Faith Mumbi",
    brandName: "Baraka Foods",
    email: "faith@barakafoods.co.ke",
    phone: "+254 715 330 776",
    location: "Industrial Area, Nairobi",
    message: "Enquiring about a follow-up commercial for our next product line.",
    services: ["Video / Commercials"],
    source: "Direct",
    dateReceived: "2026-08-27",
    status: "New",
    priority: "Normal",
    owner: "Faith Achieng",
    estimatedValue: null,
    desiredTimeline: "Next quarter",
    qualificationNotes: "",
    nextFollowUp: "2026-09-15",
    followUpNote: "Re-engagement check-in — existing client",
    notes: [],
    events: [{ id: evId(), date: "2026-08-27", type: "received", label: "Enquiry received via direct email" }],
    conversion: null,
    originCampaign: null
  }
];
